<?php
use Justuno_M1_Settings as S;
$merchantID = S::id(); /** @var string $merchantID */
$pattern = "/^[{]?[0-9a-fA-F]{8}[-]?([0-9a-fA-F]{4}[-]?){3}[0-9a-fA-F]{12}[}]?$/";
if (preg_match($pattern, $merchantID)) { ?>
	<script>
		window.ju_num='<?= $merchantID ?>';
		window.ju_ajaxCartURL = '<?= $this->getUrl('jumagext/index/getcart')?>';
		if (location.href.includes('checkout') && location.href.includes('success')) {
		   <?php
				$orderID = Mage::getSingleton('checkout/session')->getLastOrderId();
				$order = Mage::getModel('sales/order')->load($orderID);
			?>
			window.ju_order_id = '<?= $orderID ?>';
			window.ju_order_obj = {
				total: '<?= $order->getGrandTotal() ?>',
				subtotal: '<?= $order->getSubtotal() ?>',
				tax: '<?= $order->getTaxAmount() ?>',
				shipping: '<?= $order->getShippingAmount() ?>',
				currency:'<?= Mage::app()->getStore()->getCurrentCurrencyCode() ?>'
			};
		}
		else {
		  window.ju_cart_obj = {
				total: '<?= Mage::helper('checkout/cart')->getQuote()->getGrandTotal() ?>',
				subtotal: '<?= Mage::helper('checkout/cart')->getQuote()->getSubtotal() ?>',
				tax: '<?= Mage::helper('checkout/cart')->getQuote()->getTaxAmount() ?>',
				shipping: '<?= Mage::helper('checkout/cart')->getQuote()->getShippingAmount() ?>',
				currency: '<?= Mage::app()->getStore()->getCurrentCurrencyCode() ?>'
			};
		}
		window.asset_host = '//cdn.justuno.com/';
		(function (i, s, o, g, r, a, m) {
			i[r] = i[r] || function () {
				(i[r].q = i[r].q || []).push(arguments);
			};
			a = s.createElement(o);
			m = s.getElementsByTagName(o)[0];
			a.async = 1;
			a.src = g;
			m.parentNode.insertBefore(a, m);
			// eslint-disable-next-line no-undef
		})(window, document, 'script', asset_host + 'vck-m1.js', 'juapp');
	</script>
<?php } else { ?>
	<script>console.log('JU_ERROR: Justuno Account ID (ACCID) Was Not Set Correctly...');</script>
<?php }
if ($url = S::ajaxUrl()) { /** @var string $url */
	?><script>window.ju_MageAJAX = '<?= $url ?>';</script><?php
}
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
	$customerData = Mage::getSingleton('customer/session')->getCustomer();
	$customerID = $customerData->getId();
}
else {
	$customerID = null;
}
$pageIdentifier = Mage::app()->getFrontController()->getAction()->getFullActionName();
if (Mage::registry('current_product')) {
	$product = Mage::registry('current_product');
	$productid = $product->getId();
	$productstockqty = $product->getStockItem()->getQty();
}
else {
	list($productid, $productstockqty) = [null, null];
}
?>
<script>
	window.ju_MageKeys = {
		PageID: '<?= $pageIdentifier ?>',
		ProductID: '<?= $productid ?>',
		CustomerID: '<?= $customerID ?>',
		StockQty: '<?= $productstockqty ?>'
	};
</script>