<script type="text/javascript">
    //<![CDATA[
        function generateToken(){
        var rString = randomString(32, '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ');
        var s   = document.getElementById("justuno_justuno_settings_jutoken");
        s.value = rString;  
        return false;
    }

    function randomString(length, chars) {
        var result = '';
        for (var i = length; i > 0; --i) result += chars[Math.floor(Math.random() * chars.length)];
        return result;
    }

    //]]>
</script>
<?php echo $this->getButtonHtml() ?>