<script type='text/javascript'>
	function generateToken() {
		document.getElementById('justuno_justuno_settings_jutoken').value = function() {
			var r = '';
			const c = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
			const cl = c.length;
			for (let i = 32; 0 < i; i--) {
				r += c[Math.floor(cl * Math.random())];
			}
			return r;
		}();
		return false;
	}
</script>
<?= $this->getButtonHtml();